#!/system/bin/sh

user_cpu_table="/cpu_table_location"
if [ $user_cpu_table != "" -a -e $user_cpu_table ]; then	
	tmp_available_freq=(`cat $user_cpu_table`)
elif [ -e /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies ]; then	
	tmp_available_freq=(`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies`)
elif [ -e /sys/power/cpufreq_table ]; then
	tmp_available_freq=(`cat /sys/power/cpufreq_table`)
else
	tmp_available_freq=( 384000 486000 594000 702000 810000 918000 1026000 1134000 1242000 1350000 1458000 1512000 )
fi;
available_freq=()
for freq in "${tmp_available_freq[@]}";
do
	i=1
	for freq1 in "${tmp_available_freq[@]}";
	do
		if [ $freq1 -lt $freq ]; then
			i=$(($i+1))
		fi;
 	done
	available_freq[$i]=$freq
done

max_level=${#available_freq[@]}
gap_level=$(($max_level/3))
middle_level=$(($max_level-$(($gap_level/2))))
low_level=$(($max_level-$gap_level))


gpumaxlocation="no"
gclock1=0
gclock2=0
gclock3=0
gclock4=0
gpuclock=()
gpu_check="ok"

if [ $gpumaxlocation == "no" -a -e /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/max_gpuclk ]; then #g2
	gpumaxlocation="/sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/max_gpuclk"
fi;
if [ $gpumaxlocation == "no" -a -e /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk ]; then #optimus g
	gpumaxlocation="/sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk"
fi;
if [ $gpumaxlocation == "no" -a -e /sys/devices/system/gpu/max_freq ]; then #galaxy
	gpumaxlocation="/sys/devices/system/gpu/max_freq"
fi;
if [ $gpumaxlocation == "no" -a -e /sys/devices/platform/pvrsrvkm.0/sgx_dvfs_max_lock ]; then #galaxy
	gpumaxlocation="/sys/devices/platform/pvrsrvkm.0/sgx_dvfs_max_lock"
fi;

if [ -e /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/gpu_available_frequencies ]; then
	tmp_gpu_available_freq=(`cat /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/gpu_available_frequencies`)
	chmod 777 /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/*
elif [ -e /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/gpu_available_frequencies ]; then
	tmp_gpu_available_freq=(`cat /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/gpu_available_frequencies`)
	chmod 777 /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/*
elif [ -e /sys/devices/system/gpu/freq_table ]; then
	tmp_gpu_available_freq=(`cat /sys/devices/system/gpu/freq_table`)
	chmod 777 /sys/devices/system/gpu/*
elif [ -e /sys/devices/platform/pvrsrvkm.0/sgx_dvfs_table ]; then
	tmp_gpu_available_freq=(`cat /sys/devices/platform/pvrsrvkm.0/sgx_dvfs_table`)
	chmod 777 /sys/devices/platform/pvrsrvkm.0/*
else
	tmp_gpu_available_freq=( 128000000 200000000 320000000 400000000 )
fi;

set_gpu_available_freq=()
for gpu_freq in "${tmp_gpu_available_freq[@]}";
do
	i=1
	for gpu_freq1 in "${tmp_gpu_available_freq[@]}";
	do
		if [ $gpu_freq1 -lt $gpu_freq ]; then
			i=$(($i+1))
		fi;
 	done
	set_gpu_available_freq[$i]=$gpu_freq
done

gpu_available_freq=()
j=1
for gpu_freq in "${set_gpu_available_freq[@]}";
do
	gpu_available_freq[$j]=$gpu_freq
	j=$(($j+1))
done

gpu_max_level=${#gpu_available_freq[@]}
gpu_middle_level=$(($gpu_max_level-1))
gpu_low_level=$(($gpu_max_level-2))

if [ $gpumaxlocation == "no" ]; then
	busybox mount -o rw,remount /system;
	if [ ! -e /system/asc_log.txt ]; then
		touch /system/asc_log.txt
		chmod 777 /system/asc_log.txt
	fi;
	echo "gpu max_freq not found error" >> /system/asc_log.txt
	gpu_check="no"
fi;

cpu_prev_total=0
cpu_prev_idle=0
cpu_usage=0
cpu0_prev_total=0
cpu0_prev_idle=0
cpu0_usage=0
cpu1_prev_total=0
cpu1_prev_idle=0
cpu1_usage=0
cpu2_prev_total=0
cpu2_prev_idle=0
cpu2_usage=0
cpu3_prev_total=0
cpu3_prev_idle=0
cpu3_usage=0
get_cpu_usage()
{
	if [ $1 == "0" ]; then
		cpu=(`cat /proc/stat | busybox grep '^cpu0 '`)
		tmp_cpu_prev_idle=$cpu0_prev_idle
		tmp_cpu_prev_total=$cpu0_prev_total
	elif [ $1 == "1" ]; then
		cpu=(`cat /proc/stat | busybox grep '^cpu1 '`)
		tmp_cpu_prev_idle=$cpu1_prev_idle
		tmp_cpu_prev_total=$cpu1_prev_total
	elif [ $1 == "2" ]; then
		cpu=(`cat /proc/stat | busybox grep '^cpu2 '`)
		tmp_cpu_prev_idle=$cpu2_prev_idle
		tmp_cpu_prev_total=$cpu2_prev_total
	elif [ $1 == "3" ]; then
		cpu=(`cat /proc/stat | busybox grep '^cpu3 '`)
		tmp_cpu_prev_idle=$cpu3_prev_idle
		tmp_cpu_prev_total=$cpu3_prev_total
	else
		cpu=(`cat /proc/stat | busybox grep '^cpu '`)
		tmp_cpu_prev_idle=$cpu_prev_idle
		tmp_cpu_prev_total=$cpu_prev_total
	fi;
	unset cpu[0]
	idle=${cpu[4]}

	total=0
	for value in "${cpu[@]}";
	do
		total=$(($total+$value))
	done

	diff_idle=$(($idle-$tmp_cpu_prev_idle))
	diff_total=$(($total-$tmp_cpu_prev_total))
	if [ $diff_total -ne 0 ]; then
		usage=$(((1000*(($diff_total)-($diff_idle))/($diff_total)+5)/10))
		if [ $usage -ge 100 ]; then
			usage=100
		fi;
		if [ $usage -le 0 ]; then
			usage=0
		fi;
	else
		usage=0
	fi;

	if [ $1 == "0" ]; then
		cpu0_prev_idle=$idle
		cpu0_prev_total=$total
		cpu0_usage=$usage
	elif [ $1 == "1" ]; then
		cpu1_prev_idle=$idle
		cpu1_prev_total=$total
		cpu1_usage=$usage
	elif [ $1 == "2" ]; then
		cpu2_prev_idle=$idle
		cpu2_prev_total=$total
		cpu2_usage=$usage
	elif [ $1 == "3" ]; then
		cpu3_prev_idle=$idle
		cpu3_prev_total=$total
		cpu3_usage=$usage
	else
		cpu_prev_idle=$idle
		cpu_prev_total=$total
		cpu_usage=$usage
	fi;
}

ondemand="no"
cpu0_ondemand="no"
cpu1_ondemand="no"
cpu2_ondemand="no"
cpu3_ondemand="no"

cpu0_max_check="no"
cpu1_max_check="no"
cpu2_max_check="no"
cpu3_max_check="no"

gpu_limit1=20
gpu_limit2=50
gpu_count=0

if [ -e /sys/devices/system/cpu/cpu2 -a -e /sys/devices/system/cpu/cpu3 ]; then
	cpu_core="quard"
	cpu0_limit1=30
	cpu0_limit2=60
	cpu1_limit1=30
	cpu1_limit2=60
	cpu2_limit1=35
	cpu2_limit2=65
	cpu3_limit1=40
	cpu3_limit2=70
else
	cpu_core="dual"
	cpu0_limit1=40
	cpu0_limit2=70
	cpu1_limit1=40
	cpu1_limit2=70
fi;

while [ 1 ];
do
	busybox usleep 1000000
	
	if [ $cpu0_ondemand == "no" ]; then
		if [ `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor` == "ondemand" ]; then
			cpu0_ondemand="yes"
		fi;
		chmod 777 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
		echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 
	fi;
	
	get_cpu_usage 0
	cpu0_max_location="/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq"
	cpu0_max_freq=`cat $cpu0_max_location`
	
	if [ $cpu0_max_check == "yes" -a $cpu0_usage -lt $(($cpu0_limit2-20)) ]; then
		cpu0_max_check="no"
	fi;
	
	if [ $cpu0_max_check == "no" ]; then
		if [ $cpu0_usage -lt $cpu0_limit1 ]; then
			if [ $cpu0_max_freq -ne ${available_freq[$low_level]} ]; then
				echo ${available_freq[$low_level]} > $cpu0_max_location
			fi;
		elif [ $cpu0_usage -ge $cpu0_limit1 -a $cpu0_usage -lt $cpu0_limit2 ]; then
			if [ $cpu0_max_freq -ne ${available_freq[$middle_level]} ]; then
				echo ${available_freq[$middle_level]} > $cpu0_max_location
			fi;
		else
			if [ $cpu0_max_freq -ne ${available_freq[$max_level]} ]; then
				echo ${available_freq[$max_level]} > $cpu0_max_location
				cpu0_max_check="yes"
			fi;
		fi;
	fi;

	if [ `cat /sys/devices/system/cpu/cpu1/online` -eq 1 ]; then
		if [ $cpu1_ondemand == "no" ]; then
			if [ `cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor` == "ondemand" ]; then
				cpu1_ondemand="yes"
			fi;
			chmod 777 /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
			echo "ondemand" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor 		
		fi;

		get_cpu_usage 1
		cpu1_max_location="/sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq"
		cpu1_max_freq=`cat $cpu1_max_location`
		
		if [ $cpu1_max_check == "yes" -a $cpu1_usage -lt $(($cpu1_limit2-20)) ]; then
			cpu1_max_check="no"
		fi;
		
		if [ $cpu1_max_check == "no" ]; then
			if [ $cpu1_usage -lt $cpu1_limit1 ]; then
				if [ $cpu1_max_freq -ne ${available_freq[$low_level]} ]; then
					echo ${available_freq[$low_level]} > $cpu1_max_location
				fi;
			elif [ $cpu1_usage -ge $cpu1_limit1 -a $cpu1_usage -lt $cpu1_limit2 ]; then
				if [ $cpu1_max_freq -ne ${available_freq[$middle_level]} ]; then
					echo ${available_freq[$middle_level]} > $cpu1_max_location
				fi;
			else
				if [ $cpu1_max_freq -ne ${available_freq[$max_level]} ]; then
					echo ${available_freq[$max_level]} > $cpu1_max_location
					cpu1_max_check="yes"
				fi;
			fi;
		fi;
	else
		if [ $cpu1_max_check == "yes" ]; then
			cpu1_max_check="no"
		fi;
	fi;
	
	if [ $cpu_core == "quard" ]; then
		if [ `cat /sys/devices/system/cpu/cpu2/online` -eq 1 ]; then
			if [ $cpu2_ondemand == "no" ]; then
				if [ `cat /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor` == "ondemand" ]; then
					cpu2_ondemand="yes"
				fi;
				chmod 777 /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
				echo "ondemand" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor 
			fi;
		
			get_cpu_usage 2
			cpu2_max_location="/sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq"
			cpu2_max_freq=`cat $cpu2_max_location`
			
			if [ $cpu2_max_check == "yes" -a $cpu2_usage -lt $(($cpu2_limit2-20)) ]; then
				cpu2_max_check="no"
			fi;
			
			if [ $cpu2_max_check == "no" ]; then
				if [ $cpu2_usage -lt $cpu2_limit1 ]; then
					if [ $cpu2_max_freq -ne ${available_freq[$low_level]} ]; then
						echo ${available_freq[$low_level]} > $cpu2_max_location
					fi;
				elif [ $cpu2_usage -ge $cpu2_limit1 -a $cpu2_usage -lt $cpu2_limit2 ]; then
					if [ $cpu2_max_freq -ne ${available_freq[$middle_level]} ]; then
						echo ${available_freq[$middle_level]} > $cpu2_max_location
					fi;
				else
					if [ $cpu2_max_freq -ne ${available_freq[$max_level]} ]; then
						echo ${available_freq[$max_level]} > $cpu2_max_location
						cpu2_max_check="yes"
					fi;
				fi;
			fi;
		else
			if [ $cpu2_max_check == "yes" ]; then
				cpu2_max_check="no"
			fi;	
		fi;
	fi;
	
	if [ $cpu_core == "quard" ]; then
		if [ `cat /sys/devices/system/cpu/cpu3/online` -eq 1 ]; then
			if [ $cpu3_ondemand == "no" ]; then
				if [ `cat /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor` == "ondemand" ]; then
					cpu3_ondemand="yes"
				fi;
				chmod 777 /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
				echo "ondemand" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor 
			fi;
		
			get_cpu_usage 3
			cpu3_max_location="/sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq"
			cpu3_max_freq=`cat $cpu3_max_location`
			
			if [ $cpu3_max_check == "yes" -a $cpu3_usage -lt $(($cpu3_limit2-20)) ]; then
				cpu3_max_check="no"
			fi;
			
			if [ $cpu3_max_check == "no" ]; then
				if [ $cpu3_usage -lt $cpu3_limit1 ]; then
					if [ $cpu3_max_freq -ne ${available_freq[$low_level]} ]; then
						echo ${available_freq[$low_level]} > $cpu3_max_location
					fi;
				elif [ $cpu3_usage -ge $cpu3_limit1 -a $cpu3_usage -lt $cpu3_limit2 ]; then
					if [ $cpu3_max_freq -ne ${available_freq[$middle_level]} ]; then
						echo ${available_freq[$middle_level]} > $cpu3_max_location
					fi;
				else
					if [ $cpu3_max_freq -ne ${available_freq[$max_level]} ]; then
						echo ${available_freq[$max_level]} > $cpu3_max_location
						cpu3_max_check="yes"
					fi;
				fi;
			fi;
		else
			if [ $cpu3_max_check == "yes" ]; then
				cpu3_max_check="no"	
			fi;
		fi;
	fi;

	get_cpu_usage all

	if [ $gpu_check == "ok" ]; then
		if [ $gpu_count -le 0 ]; then
			gpu_max_clk=`cat $gpumaxlocation`
			if [ $cpu_usage -ne 0 ]; then
				if [ $cpu_usage -lt $gpu_limit1 ]; then
					if [ $gpu_max_clk -ne ${gpu_available_freq[$gpu_low_level]} ]; then
						echo ${gpu_available_freq[$gpu_low_level]} > $gpumaxlocation
					fi;
				elif [ $cpu_usage -ge $gpu_limit1 -a $cpu_usage -le $gpu_limit2 ]; then
					if [ $gpu_max_clk -ne ${gpu_available_freq[$gpu_middle_level]} ]; then
						echo ${gpu_available_freq[$gpu_middle_level]} > $gpumaxlocation
					fi;
				else
					if [ $gpu_max_clk -ne ${gpu_available_freq[$gpu_max_level]} ]; then
						echo ${gpu_available_freq[$gpu_max_level]} > $gpumaxlocation
						gpu_count=1
					fi;		
				fi;
			fi;
		else
			gpu_count=$(($gpu_count-1))
		fi;
	fi;
	
	if [ $ondemand == "no" -a $cpu0_ondemand == "yes" ]; then
		chmod 777 /sys/devices/system/cpu/cpufreq/ondemand/*

		if [ -e /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_any_cpu_load ]; then
			echo "13" > /sys/devices/system/cpu/cpufreq/ondemand/down_differential
			echo "1" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
			echo "98" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
		else
			echo "10" > /sys/devices/system/cpu/cpufreq/ondemand/down_differential
			echo "1" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
			echo "95" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
		fi;

		echo "85" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_any_cpu_load
		echo "960000" > /sys/devices/system/cpu/cpufreq/ondemand/sync_freq
		echo "75" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_multi_core
		echo "960000" > /sys/devices/system/cpu/cpufreq/ondemand/optimal_freq
		echo "960000" > /sys/devices/system/cpu/cpufreq/ondemand/optimal_max_freq
			
		echo "60" > /sys/devices/system/cpu/cpufreq/ondemand/high_grid_load
		echo "14" > /sys/devices/system/cpu/cpufreq/ondemand/high_grid_step
		echo "50" > /sys/devices/system/cpu/cpufreq/ondemand/middle_grid_load
		echo "7" > /sys/devices/system/cpu/cpufreq/ondemand/middle_grid_step
		ondemand="yes"
	fi;
done;